//User types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const SET_USER_TEAM = 'SET_USER_TEAM';
export const SET_USERS_BY_POINTS = 'SET_USERS_BY_POINTS';
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const GET_USER_LEAGUES = 'GET_USER_LEAGUES';
export const LOADING_POINTS = 'LOADING_POINTS';
export const CLEAR_LOADING_POINTS = 'CLEAR_LOADING_POINTS';
export const GET_USER_TEAM = 'GET_USER_TEAM';
export const CLEAR_USER_TEAM = 'CLEAR_USER_TEAM';

//UI types
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const POSITIVE_MESSAGES = 'POSITIVE_MESSAGES';

//Data types
export const SET_PLAYERS = 'SET_PLAYERS';
export const LOADING_DATA = 'LOADING_DATA';
export const SET_PLAYER = 'SET_PLAYER';
export const CREATE_PLAYER = 'CREATE_PLAYER';
export const LOADING_PLAYERS = 'LOADING_PLAYERS';
export const CLEAR_LOADING_PLAYERS = 'CLEAR_LOADING_PLAYERS';




