//User types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const SET_USER_TEAM = 'SET_USER_TEAM';
export const SET_USERS_BY_POINTS = 'SET_USERS_BY_POINTS';
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const GET_USER_LEAGUES = 'GET_USER_LEAGUES';
export const LOADING_POINTS = 'LOADING_POINTS';
export const CLEAR_LOADING_POINTS = 'CLEAR_LOADING_POINTS';
export const GET_USER_TEAM = 'GET_USER_TEAM';
export const CLEAR_USER_TEAM = 'CLEAR_USER_TEAM';
export const LOADING_PUBLIC_USER_LEAGUES = 'LOADING_PUBLIC_USER_LEAGUES';
export const CLEAR_LOADING_PUBLIC_USER_LEAGUES = 'CLEAR_LOADING_PUBLIC_USER_LEAGUES';
export const GET_PUBLIC_USER_LEAGUES = 'GET_PUBLIC_USER_LEAGUES';

//UI types
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const POSITIVE_MESSAGES = 'POSITIVE_MESSAGES';

//Data types
export const SET_PLAYERS = 'SET_PLAYERS';
export const LOADING_DATA = 'LOADING_DATA';
export const SET_PLAYER = 'SET_PLAYER';
export const CREATE_PLAYER = 'CREATE_PLAYER';
export const LOADING_PLAYERS = 'LOADING_PLAYERS';
export const CLEAR_LOADING_PLAYERS = 'CLEAR_LOADING_PLAYERS';

//League types
export const LOADING_CREATE_LEAGUE = 'LOADING_CREATE_LEAGUE';
export const CLEAR_LOADING_CREATE_LEAGUE = 'CLEAR_LOADING_CREATE_LEAGUE';
export const CREATE_LEAGUE = 'CREATE_LEAGUE';
export const LOADING_ADD_FRIEND_TO_LEAGUE = 'LOADING_ADD_FRIEND_TO_LEAGUE';
export const CLEAR_LOADING_ADD_FRIEND_TO_LEAGUE = 'CLEAR_LOADING_ADD_FRIEND_TO_LEAGUE';
export const ADD_FRIEND_TO_LEAGUE = 'ADD_FRIEND_TO_LEAGUE';
export const LOADING_PUBLIC_LEAGUE = 'LOADING_PUBLIC_LEAGUE';
export const CLEAR_LOADING_PUBLIC_LEAGUE = 'CLEAR_LOADING_PUBLIC_LEAGUE';
export const GET_PUBLIC_LEAGUE = 'GET_PUBLIC_LEAGUE';
export const LOADING_REMOVE_USER_FROM_LEAGUE = 'LOADING_REMOVE_USER_FROM_LEAGUE';
export const CLEAR_LOADING_REMOVE_USER_FROM_LEAGUE = 'CLEAR_LOADING_REMOVE_USER_FROM_LEAGUE';
export const DELETING_USER_FROM_LEAGUE = 'DELETING_USER_FROM_LEAGUE';




